### Data Wrangling2

###`.map()`

In [88]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/automobile_data_nan.csv', index_col = 'index')
df

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [ ]:
df['num-of-cylinders'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [ ]:
dictt = {'four':4, 'six':6, 'five':5, 'twelve':12, 'two':2, 'eight':8, 'three':3}
df['cylinders'] = df['num-of-cylinders'].map(dictt)
df

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders,price_uzs
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0,4,171386500
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0,4,209550000
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0,6,209550000
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0,4,177165000
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5,221615000
...,...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0,4,101282500
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0,4,101536500
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0,4,126936500
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0,4,164338000
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0,4,170370500

In [ ]:
uzs = 12700
df['price_uzs'] = df['price'].map(lambda x: x * uzs)
df['price_uzs'] = df['price_uzs'].fillna(np.mean(df['price_uzs']))
df['price_uzs'] = df['price_uzs'].astype(np.int32)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders,price_uzs
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0,4,171386500
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0,4,209550000
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0,6,209550000
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0,4,177165000
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5,221615000

###`.replace()`

In [ ]:
df.replace({'six':6})

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders,price_uzs
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0,4,171386500
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0,4,209550000
2,alfa-romero,hatchback,94.5,171.2,ohcv,6,154.0,NaN,16500.0,6,209550000
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0,4,177165000
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5,221615000
...,...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0,4,101282500
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0,4,101536500
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0,4,126936500
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0,4,164338000
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0,4,170370500

In [ ]:
df.replace(dictt)

/tmp/ipython-input-4001356565.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(dictt)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders,price_uzs
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,4,NaN,21.0,13495.0,4,171386500
1,alfa-romero,convertible,NaN,168.8,dohc,4,111.0,21.0,16500.0,4,209550000
2,alfa-romero,hatchback,94.5,171.2,ohcv,6,154.0,NaN,16500.0,6,209550000
3,audi,sedan,99.8,176.6,ohc,4,102.0,24.0,13950.0,4,177165000
4,audi,sedan,99.4,176.6,ohc,5,NaN,NaN,17450.0,5,221615000
...,...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,4,85.0,27.0,7975.0,4,101282500
82,volkswagen,sedan,NaN,171.7,NaN,4,52.0,37.0,7995.0,4,101536500
86,volkswagen,sedan,97.3,NaN,ohc,4,100.0,NaN,9995.0,4,126936500
87,volvo,sedan,104.3,188.8,NaN,4,114.0,23.0,12940.0,4,164338000
88,volvo,wagon,104.3,188.8,ohc,4,NaN,23.0,13415.0,4,170370500

###`.rename()`

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/world_population.csv', index_col = 'country')
df.head()

           rank     density   densityMi   pop2021  area
country
Macau         1  21946.4667  56841.3487   658.394    30
Monaco        2  19755.5000  51166.7450    39.511     2
Singapore     3   8305.1915  21510.4461  5896.686   710
Hong Kong     4   6841.3134  17719.0017  7552.810  1104
Gibraltar     5   5616.3333  14546.3033    33.698     6

In [ ]:
df.rename(columns = str.upper)

                  RANK     DENSITY   DENSITYMI   POP2021     AREA
country
Macau                1  21946.4667  56841.3487   658.394       30
Monaco               2  19755.5000  51166.7450    39.511        2
Singapore            3   8305.1915  21510.4461  5896.686      710
Hong Kong            4   6841.3134  17719.0017  7552.810     1104
Gibraltar            5   5616.3333  14546.3033    33.698        6
...                ...         ...         ...       ...      ...
Namibia            228      3.1338      8.1166  2587.344   825615
Western Sahara     229      2.3003      5.9577   611.875   266000
Mongolia           230      2.1286      5.5129  3329.289  1564110
Falkland Islands   231      0.2902      0.7517     3.533    12173
Greenland          232      0.0263      0.0680    56.877  2166086

[232 rows x 5 columns]

In [ ]:
df.rename(index = str.upper)

                  rank     density   densityMi   pop2021     area
country
MACAU                1  21946.4667  56841.3487   658.394       30
MONACO               2  19755.5000  51166.7450    39.511        2
SINGAPORE            3   8305.1915  21510.4461  5896.686      710
HONG KONG            4   6841.3134  17719.0017  7552.810     1104
GIBRALTAR            5   5616.3333  14546.3033    33.698        6
...                ...         ...         ...       ...      ...
NAMIBIA            228      3.1338      8.1166  2587.344   825615
WESTERN SAHARA     229      2.3003      5.9577   611.875   266000
MONGOLIA           230      2.1286      5.5129  3329.289  1564110
FALKLAND ISLANDS   231      0.2902      0.7517     3.533    12173
GREENLAND          232      0.0263      0.0680    56.877  2166086

[232 rows x 5 columns]

In [ ]:
df = df.rename(index = str.title, columns = str.title)
df.head(9)

              Rank     Density   Densitymi   Pop2021  Area
country
Macau            1  21946.4667  56841.3487   658.394    30
Monaco           2  19755.5000  51166.7450    39.511     2
Singapore        3   8305.1915  21510.4461  5896.686   710
Hong Kong        4   6841.3134  17719.0017  7552.810  1104
Gibraltar        5   5616.3333  14546.3033    33.698     6
Bahrain          6   2285.3542   5919.0675  1748.296   765
Maldives         7   1812.0567   4693.2268   543.617   300
Malta            8   1401.2152   3629.1473   442.784   316
Sint Maarten     9   1276.8235   3306.9729    43.412    34

In [ ]:
df = df.rename(columns = {'Pop2021':'Population', 'Densitymi':'Density'})
df.head()

           Rank     Density     Density  Population  Area
country
Macau         1  21946.4667  56841.3487     658.394    30
Monaco        2  19755.5000  51166.7450      39.511     2
Singapore     3   8305.1915  21510.4461    5896.686   710
Hong Kong     4   6841.3134  17719.0017    7552.810  1104
Gibraltar     5   5616.3333  14546.3033      33.698     6

### `.cut()`

In [ ]:
df['Population'] = df['Population'].astype(np.int16)
df.head()

           Rank     Density     Density  Population  Area
country
Macau         1  21946.4667  56841.3487         658    30
Monaco        2  19755.5000  51166.7450          39     2
Singapore     3   8305.1915  21510.4461        5896   710
Hong Kong     4   6841.3134  17719.0017        7552  1104
Gibraltar     5   5616.3333  14546.3033          33     6

In [ ]:
df.describe()

             Rank       Density       Density    Population          Area
count  232.000000    232.000000    232.000000    232.000000  2.320000e+02
mean   116.500000    450.585827   1167.017293   3716.767241  5.864610e+05
std     67.116814   2078.591351   5383.551600  12390.977859  1.768617e+06
min      1.000000      0.026300      0.068000 -32760.000000  1.000000e+00
25%     58.750000     35.442775     91.796750     65.000000  3.735250e+03
50%    116.500000     95.418750    247.134600   2218.500000  8.356700e+04
75%    174.250000    240.029700    621.676950  10008.750000  4.403752e+05
max    232.000000  21946.466700  56841.348700  32632.000000  1.709824e+07

In [ ]:
bins = [0, 1000, 4000]
groups = pd.cut(df['Population'], bins)
groups.value_counts()

Population
(0, 1000]       71
(1000, 4000]    31
Name: count, dtype: int64

In [ ]:
df = df[df['Population'] >= 0]
groups = pd.cut(df['Population'], 3)
groups

country
Macau               (-32.632, 10877.333]
Monaco              (-32.632, 10877.333]
Singapore           (-32.632, 10877.333]
Hong Kong           (-32.632, 10877.333]
Gibraltar           (-32.632, 10877.333]
                            ...
Namibia             (-32.632, 10877.333]
Western Sahara      (-32.632, 10877.333]
Mongolia            (-32.632, 10877.333]
Falkland Islands    (-32.632, 10877.333]
Greenland           (-32.632, 10877.333]
Name: Population, Length: 202, dtype: category
Categories (3, interval[float64, right]): [(-32.632, 10877.333] < (10877.333, 21754.667] <
                                           (21754.667, 32632.0]]

In [ ]:
groups.value_counts()

Population
(-32.632, 10877.333]      151
(10877.333, 21754.667]     36
(21754.667, 32632.0]       15
Name: count, dtype: int64

`lables=`

In [ ]:
bins = [0, 100000, 500000, 1000000, 5000000, 10000000, 20000000]
new = pd.cut(df['Area'], bins)
new.head()

country
Macau        (0, 100000]
Monaco       (0, 100000]
Singapore    (0, 100000]
Hong Kong    (0, 100000]
Gibraltar    (0, 100000]
Name: Area, dtype: category
Categories (6, interval[int64, right]): [(0, 100000] < (100000, 500000] < (500000, 1000000] <
                                         (1000000, 5000000] < (5000000, 10000000] <
                                         (10000000, 20000000]]

In [ ]:
new.value_counts()

Area
(0, 100000]             123
(100000, 500000]         46
(500000, 1000000]        15
(1000000, 5000000]       13
(5000000, 10000000]       4
(10000000, 20000000]      1
Name: count, dtype: int64

In [ ]:
names = ['Low', 'Middle', 'High']
bins = [0, 100000, 5000000, 20000000]

In [ ]:
group = pd.cut(df['Area'], bins, labels = names)
group

country
Macau                  Low
Monaco                 Low
Singapore              Low
Hong Kong              Low
Gibraltar              Low
                     ...
Namibia             Middle
Western Sahara      Middle
Mongolia            Middle
Falkland Islands       Low
Greenland           Middle
Name: Area, Length: 202, dtype: category
Categories (3, object): ['Low' < 'Middle' < 'High']

In [ ]:
group.value_counts()

Area
Low       123
Middle     74
High        5
Name: count, dtype: int64

### `.qcut()`

In [ ]:
df.columns

Index(['Rank', 'Density', 'Density', 'Population', 'Area'], dtype='object')

In [ ]:
qcut = pd.qcut(df['Area'], 2)
qcut

country
Macau                    (0.999, 46949.0]
Monaco                   (0.999, 46949.0]
Singapore                (0.999, 46949.0]
Hong Kong                (0.999, 46949.0]
Gibraltar                (0.999, 46949.0]
                            ...
Namibia             (46949.0, 17098242.0]
Western Sahara      (46949.0, 17098242.0]
Mongolia            (46949.0, 17098242.0]
Falkland Islands         (0.999, 46949.0]
Greenland           (46949.0, 17098242.0]
Name: Area, Length: 202, dtype: category
Categories (2, interval[float64, right]): [(0.999, 46949.0] < (46949.0, 17098242.0]]

### `.groupby()`

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/automobile_data.csv', index_col = 'index')
df

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [ ]:
df.groupby(['company', 'body-style']).min()

                           wheel-base  length engine-type num-of-cylinders  \
company       body-style
alfa-romero   convertible        88.6   168.8        dohc             four
              hatchback          94.5   171.2        ohcv              six
audi          sedan              99.4   176.6         ohc             five
              wagon             105.8   192.7         ohc             five
bmw           sedan             101.2   176.8         ohc             four
chevrolet     hatchback          88.4   141.1           l             four
              sedan              94.5   158.8         ohc             four
dodge         hatchback          93.7   157.3         ohc             four
honda         sedan              96.5   169.1         ohc             four
              wagon              96.5   157.1         ohc             four
isuzu         sedan              94.3   155.9         ohc             four
jaguar        sedan             102.0   191.7        dohc              six
mazda         hatchback          93.1   159.1         ohc             four
              sedan             104.9   175.0         ohc             four
mercedes-benz hardtop           112.0   199.2        ohcv            eight
              sedan             110.0   190.9         ohc            eight
              wagon             110.0   190.9         ohc             five
mitsubishi    hatchback          93.7   157.3         ohc             four
              sedan              96.3   172.4         ohc             four
nissan        sedan              94.5   165.3         ohc             four
              wagon              94.5   170.2         ohc             four
porsche       convertible        89.5   168.9        ohcf              six
              hardtop            89.5   168.9        ohcf              six
              hatchback          98.4   175.7       dohcv            eight
toyota        hatchback          95.7   158.7         ohc             four
              wagon              95.7   169.7        dohc             four
volkswagen    sedan              97.3   171.7         ohc             four
volvo         sedan             104.3   188.8         ohc             four
              wagon             104.3   188.8         ohc             four

                           horsepower  average-mileage    price
company       body-style
alfa-romero   convertible         111               21  13495.0
              hatchback           154               19  16500.0
audi          sedan               102               18  13950.0
              wagon               110               19  18920.0
bmw           sedan               101               15  16430.0
chevrolet     hatchback            48               38   5151.0
              sedan                70               38   6575.0
dodge         hatchback            68               31   6229.0
honda         sedan               100               24  10345.0
              wagon                76               30   7295.0
isuzu         sedan                70               24   6785.0
jaguar        sedan               176               13  32250.0
mazda         hatchback            68               17   5195.0
              sedan                72               31  18344.0
mercedes-benz hardtop             184               14  45400.0
              sedan               123               14  25552.0
              wagon               123               22  28248.0
mitsubishi    hatchback            68               31   5389.0
              sedan                88               25   6989.0
nissan        sedan                55               19   6649.0
              wagon                69               31   7349.0
porsche       convertible         207               17  37028.0
              hardtop             207               17  34028.0
              hatchback           288               17      NaN
toyota        hatchback            62               31   5348.0
              wagon                62               19   6918.0
volkswagen    sedan                52               26   7775.0
volvo         sedan               114               23  12940.0
              wagon               114               23  13415.0

In [ ]:
df[(df['company'] == 'alfa-romero') & (df['body-style'] == 'convertible')]['horsepower'].min()

111

In [ ]:
df.groupby('company')['price'].mean()

company
alfa-romero      15498.333333
audi             16392.500000
bmw              27213.333333
chevrolet         6007.000000
dodge             6303.000000
honda            10195.000000
isuzu             6785.000000
jaguar           34600.000000
mazda             9654.800000
mercedes-benz    35040.000000
mitsubishi        6689.000000
nissan            8289.000000
porsche          35528.000000
toyota            8216.857143
volkswagen        8435.000000
volvo            13177.500000
Name: price, dtype: float64

### `.agg([])`

In [ ]:
df.groupby('company')[['horsepower', 'average-mileage', 'price', 'wheel-base', 'length']].agg([min, max])

/tmp/ipython-input-617407811.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby('company')[['horsepower', 'average-mileage', 'price', 'wheel-base', 'length']].agg([min, max])
/tmp/ipython-input-617407811.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby('company')[['horsepower', 'average-mileage', 'price', 'wheel-base', 'length']].agg([min, max])
/tmp/ipython-input-617407811.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby('company')[['horsepower', 'average-mileage', 'price', 'wheel-base', 'length']].agg([min, max])

              horsepower      average-mileage        price           \
                     min  max             min max      min      max
company
alfa-romero          111  154              19  21  13495.0  16500.0
audi                 102  115              18  24  13950.0  18920.0
bmw                  101  182              15  23  16430.0  41315.0
chevrolet             48   70              38  47   5151.0   6575.0
dodge                 68   68              31  31   6229.0   6377.0
honda                 76  101              24  30   7295.0  12945.0
isuzu                 70   78              24  38   6785.0   6785.0
jaguar               176  262              13  15  32250.0  36000.0
mazda                 68  101              17  31   5195.0  18344.0
mercedes-benz        123  184              14  22  25552.0  45400.0
mitsubishi            68   88              25  37   5389.0   8189.0
nissan                55  152              19  45   6649.0  13499.0
porsche              207  288              17  17  34028.0  37028.0
toyota                62  156              19  35   5348.0  15750.0
volkswagen            52  100              26  37   7775.0   9995.0
volvo                114  114              23  23  12940.0  13415.0

              wheel-base        length
                     min    max    min    max
company
alfa-romero         88.6   94.5  168.8  171.2
audi                99.4  105.8  176.6  192.7
bmw                101.2  110.0  176.8  197.0
chevrolet           88.4   94.5  141.1  158.8
dodge               93.7   93.7  157.3  157.3
honda               96.5   96.5  157.1  175.4
isuzu               94.3   94.5  155.9  170.7
jaguar             102.0  113.0  191.7  199.6
mazda               93.1  104.9  159.1  175.0
mercedes-benz      110.0  120.9  190.9  208.1
mitsubishi          93.7   96.3  157.3  172.4
nissan              94.5  100.4  165.3  184.6
porsche             89.5   98.4  168.9  175.7
toyota              95.7  104.5  158.7  187.8
volkswagen          97.3   97.3  171.7  171.7
volvo              104.3  104.3  188.8  188.8

### Additional Functions

In [102]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/MOCK_USER_DATA.csv', index_col = 'id')
df.head()

   first_name   last_name                           email       gender   age
id
1     Dorothy     Verryan               dverryan0@who.int   Non-binary     1
2     Pietrek     Scanlin          pscanlin1@yolasite.com         Male    91
3      Lilith    Sarjeant  lsarjeant2@creativecommons.org  Genderfluid  1233
4        Knox  Cunningham    kcunningham3@yellowpages.com  Genderfluid     6
5    Mohammed  Habbershon    mhabbershon4@sourceforge.net       Female    48

We can note that in age column sth is going wrong. Max age of the person in history is 123 and min 1 so - 85 is wrong

In [103]:
df.describe()

               age
count   100.000000
mean    145.660000
std     565.631411
min     -85.000000
25%      22.750000
50%      53.500000
75%      84.250000
max    4444.000000

In [104]:
df['age'] = df['age'].apply(abs)
indx = df[df['age'] > 123].index
indx

Index([3, 39, 47, 49, 65, 80, 100], dtype='int64', name='id')

In [105]:
df.drop(index = indx, inplace = True)
df.head()

   first_name   last_name                         email       gender  age
id
1     Dorothy     Verryan             dverryan0@who.int   Non-binary    1
2     Pietrek     Scanlin        pscanlin1@yolasite.com         Male   91
4        Knox  Cunningham  kcunningham3@yellowpages.com  Genderfluid    6
5    Mohammed  Habbershon  mhabbershon4@sourceforge.net       Female   48
6       Glynn      Ebbing        gebbing5@rakuten.co.jp  Genderfluid   77

Now we can see max and min age values are appropriate

In [106]:
df.describe()

              age
count   93.000000
mean    52.612903
std     29.978265
min      1.000000
25%     29.000000
50%     52.000000
75%     77.000000
max    100.000000

But now gender column has variety types, we only need `Male` and `Female`

In [108]:
df['gender'].value_counts()

gender
Male           21
Bigender       12
Female         11
Genderfluid    11
Non-binary     10
Genderqueer    10
Agender         9
Polygender      9
Name: count, dtype: int64

In [109]:
df = df[df['gender'].isin(['Male', 'Female'])]
df.head()

   first_name    last_name                         email  gender  age
id
2     Pietrek      Scanlin        pscanlin1@yolasite.com    Male   91
5    Mohammed   Habbershon  mhabbershon4@sourceforge.net  Female   48
10      David     Meredyth    dmeredyth9@telegraph.co.uk  Female   68
12  Raffaello    Firminger     rfirmingerb@bloomberg.com  Female   74
17      Byram  Martynikhin     bmartynikhing@jiathis.com    Male   40

In [112]:
df.columns = df.columns.str.title()
df['Gender'].value_counts()

Gender
Male      21
Female    11
Name: count, dtype: int64

In [113]:
df.head(9)

   First_Name    Last_Name                         Email  Gender  Age
id
2     Pietrek      Scanlin        pscanlin1@yolasite.com    Male   91
5    Mohammed   Habbershon  mhabbershon4@sourceforge.net  Female   48
10      David     Meredyth    dmeredyth9@telegraph.co.uk  Female   68
12  Raffaello    Firminger     rfirmingerb@bloomberg.com  Female   74
17      Byram  Martynikhin     bmartynikhing@jiathis.com    Male   40
19      Luisa    Bradborne          lbradbornei@fema.gov  Female   75
22        Ray        Padly           rpadlyl@twitpic.com    Male   85
26   Ephrayim   Westmacott         ewestmacottp@ning.com    Male   77
29      Biron     Acklands        backlandss@comsenz.com    Male   13

### df shaffling `.random.permutation()`

In [118]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/MOCK_USER_DATA.csv', index_col = 'id')
df.head()

   first_name   last_name                           email       gender   age
id
1     Dorothy     Verryan               dverryan0@who.int   Non-binary     1
2     Pietrek     Scanlin          pscanlin1@yolasite.com         Male    91
3      Lilith    Sarjeant  lsarjeant2@creativecommons.org  Genderfluid  1233
4        Knox  Cunningham    kcunningham3@yellowpages.com  Genderfluid     6
5    Mohammed  Habbershon    mhabbershon4@sourceforge.net       Female    48

In [122]:
len(df)

100

In [126]:
listt = np.random.permutation(100)
listt

array([14, 24,  4, 25,  1, 74, 99, 30, 28, 78, 80, 17, 98, 73, 72, 31, 58,
       75,  8, 45, 63, 15, 90, 56, 52, 43, 46, 33, 57, 82, 89, 21, 81, 54,
       18, 84, 95, 23, 97, 36, 32, 85, 22, 71, 62, 35, 67, 91, 64, 93, 27,
       55, 60, 86, 26, 92, 66, 96,  9, 13, 94, 12, 83, 65, 61, 41, 87, 53,
       48, 11, 88,  5, 19,  7, 39,  2, 16, 40,  3, 49, 38,  6, 44, 20, 42,
       76, 51, 68, 29, 10, 50, 77, 69, 79, 37,  0, 70, 34, 47, 59])

In [128]:
df.take(listt)

   first_name   last_name                         email       gender  age
id
15       Suzy     Bortoli           sbortolie@opera.com      Agender  100
25    Phaedra      Guslon      pguslono@studiopress.com  Genderqueer   18
5    Mohammed  Habbershon  mhabbershon4@sourceforge.net       Female   48
26   Ephrayim  Westmacott         ewestmacottp@ning.com         Male   77
2     Pietrek     Scanlin        pscanlin1@yolasite.com         Male   91
..        ...         ...                           ...          ...  ...
1     Dorothy     Verryan             dverryan0@who.int   Non-binary    1
71       Zane    Brickham    zbrickham1y@soundcloud.com  Genderqueer    5
35    Deeanne    Iamittii          diamittiiy@nifty.com     Bigender   39
48  Sutherlan      Duigan             sduigan1b@ask.com   Non-binary   27
60  Geraldine      Beddie       gbeddie1n@earthlink.net     Bigender   86

[100 rows x 5 columns]

In [129]:
df.sample(10)

   first_name   last_name                         email       gender  age
id
52     Tillie    Winslett   twinslett1f@theatlantic.com   Non-binary   90
91      Judas      Maffin         jmaffin2i@dropbox.com         Male    3
75       Andy     Belchem      abelchem22@artisteer.com  Genderfluid   37
18    Artemus    Shovelin         ashovelinh@sphinn.com   Non-binary   58
43       Bili   Swetenham        bswetenham16@europa.eu         Male   23
35    Deeanne    Iamittii          diamittiiy@nifty.com     Bigender   39
32  Mirabelle  Matthewson  mmatthewsonv@list-manage.com      Agender   44
96       Baxy       Marcu      bmarcu2n@list-manage.com      Agender   64
2     Pietrek     Scanlin        pscanlin1@yolasite.com         Male   91
86    Rogerio        Akid           rakid2d@latimes.com       Female    3

In [130]:
df.sample(10, replace = True) # can take same rows

   first_name   last_name                         email       gender  age
id
27    Natalee     Baudone        nbaudoneq@marriott.com  Genderqueer   74
4        Knox  Cunningham  kcunningham3@yellowpages.com  Genderfluid    6
83      Randy    Bauldrey          rbauldrey2a@jugem.jp     Bigender   81
24       Mart      Brosel              mbroseln@cdc.gov  Genderfluid   22
15       Suzy     Bortoli           sbortolie@opera.com      Agender  100
76      Misty       Blanc         mblanc23@amazon.co.jp         Male   74
69      Ruthy     Bessett      rbessett1w@google.com.hk  Genderqueer    7
69      Ruthy     Bessett      rbessett1w@google.com.hk  Genderqueer    7
43       Bili   Swetenham        bswetenham16@europa.eu         Male   23
81       Alex       Darth    adarth28@ezinearticles.com       Female   98