### Data Cleaning

In [1]:
import pandas as pd

In [2]:
dataf = pd.DataFrame(
    {'OrderID': [1001, 1002, 1003, 1004, 1004, 1005, 1006, 1007, 1008, 1009],
    'Date': ['2025-01-10', '2025/02/15', '15-03-2025', '2025-04-01', '2025-04-01',
             '2025-05-12', '', '2025-06-20', '2025-06-22', '2025-07-01'],
    'City': ['Tashkent', 'Samarkand', 'Bukhara', 'Tashkent', 'Tashkent',
             'Samarkand', 'Tashkent', 'Bukhara', 'Bukhara', 'Tashkent'],
    'Product': ['Samsung A54', 'MacBook Air', 'iPhone 13', 'HP Laptop', 'HP Laptop',
                'Samsung A54', 'N/A', 'Dell XPS 13', 'iPhone 13', 'MacBook Air'],
    'Revenue': ['250', '900', '850', 'seven hundred', '700',
                '250', '300', '1100', '', '900'],
    'UnitsSold': [1.0, 1.0, 1.0, 1.0, 1.0,
                  1.0, '', 2.0, 1.0, 1.0],
    'CustomerAge': [28, 35, 32, 'thirty', 30,
                    28, 25, 40, 31, 35]}
                     )

In [3]:
dataf

,OrderID,Date,City,Product,Revenue,UnitsSold,CustomerAge
0,1001,2025-01-10,Tashkent,Samsung A54,250,1.0,28
1,1002,2025/02/15,Samarkand,MacBook Air,900,1.0,35
2,1003,15-03-2025,Bukhara,iPhone 13,850,1.0,32
3,1004,2025-04-01,Tashkent,HP Laptop,seven hundred,1.0,thirty
4,1004,2025-04-01,Tashkent,HP Laptop,700,1.0,30
5,1005,2025-05-12,Samarkand,Samsung A54,250,1.0,28
6,1006,,Tashkent,N/A,300,,25
7,1007,2025-06-20,Bukhara,Dell XPS 13,1100,2.0,40
8,1008,2025-06-22,Bukhara,iPhone 13,,1.0,31
9,1009,2025-07-01,Tashkent,MacBook Air,900,1.0,35

This table is completely messed up, emplty cells, inappropriate format, NA, duplicate rows etc.

- We can start by deleting all the duplicate rows as it may cause a serious effects on the eficiancy and memory related staff of our DataFrame.

- If having no negative effects, the best way is gonna be to delete tha rows with empty cells, however, if it is possible to get an appropriate value for an empty cell, we just can complete all of them.

- In some rows we can see incorrect format. As this table is not that big we can just replace them with its integer format using DataFrame indexes. In the case, having a huge table, better way to clean this up would be, replacing all these strings in int column with zeros(my opinion).