### Inserting tables in to a DataBase using pandas

In [2]:
import pandas as pd
import sqlite3 as sql
import numpy as np

In [3]:
db = sql.connect('Auto.db')
cursor = db.cursor()

Reading CSV

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/automobile_data.csv', index_col = 'index')
df

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [5]:
cols = ['company', 'body', 'wheel', 'length', 'engine', 'cylinders', 'horse', 'milage', 'price']
df.columns = cols
df.head()

,company,body,wheel,length,engine,cylinders,horse,milage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

A bit manipulation

In [6]:
df['price'] = df['price'].replace({np.nan:0})
df['price'] = df['price'].astype(np.int16)
df

,company,body,wheel,length,engine,cylinders,horse,milage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975
82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995
86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995
87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940
88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415

In [7]:
df.to_sql('auto_info', db)

61

Another db

In [8]:
df2 = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/car_details.csv', index_col = 'name')
df2

,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
name,,,,,,,,,,,,
Volvo XC90 T8 Excellence BSIV,2017,10000000,30000,Petrol,Individual,Automatic,First Owner,42.0,1969.0,400.0,640Nm@ 1740rpm,4.0
Mercedes-Benz S-Class S 350 CDI,2017,5850000,47000,Diesel,Dealer,Automatic,First Owner,13.5,2987.0,282.0,490Nm@ 1600rpm,5.0
Jeep Wrangler 2016-2019 3.6 4X4,2017,4100000,17000,Petrol,Individual,Automatic,First Owner,9.5,3604.0,280.0,347Nm@ 4300rpm,5.0
Jeep Wrangler 2016-2019 3.6 4X4,2017,4100000,17000,Petrol,Individual,Automatic,First Owner,9.5,3604.0,280.0,347Nm@ 4300rpm,5.0
Jeep Wrangler 2016-2019 3.6 4X4,2017,4100000,17000,Petrol,Individual,Automatic,First Owner,9.5,3604.0,280.0,347Nm@ 4300rpm,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
Toyota Qualis Fleet A3,2000,200000,100000,Diesel,Individual,Manual,First Owner,NaN,NaN,NaN,NaN,NaN
Hyundai Santro LS zipPlus,2000,140000,50000,Petrol,Individual,Manual,Second Owner,NaN,NaN,NaN,NaN,NaN
Hyundai Santro Xing XS eRLX Euro III,2006,145000,80000,Petrol,Individual,Manual,Second Owner,NaN,NaN,NaN,NaN,NaN
Ford Figo Aspire Facelift,2017,580000,165000,Diesel,Individual,Manual,First Owner,NaN,NaN,NaN,NaN,NaN
Maruti Swift 1.3 VXi,2006,130000,100000,Petrol,Individual,Manual,Second Owner,NaN,NaN,NaN,NaN,NaN

In [9]:
col = ['year', 'sell', 'km', 'fuel', 'seller', 'transmission', 'owner', 'mileage', 'engine', 'power', 'torque', 'seats']
df2.columns = col
df2

,year,sell,km,fuel,seller,transmission,owner,mileage,engine,power,torque,seats
name,,,,,,,,,,,,
Volvo XC90 T8 Excellence BSIV,2017,10000000,30000,Petrol,Individual,Automatic,First Owner,42.0,1969.0,400.0,640Nm@ 1740rpm,4.0
Mercedes-Benz S-Class S 350 CDI,2017,5850000,47000,Diesel,Dealer,Automatic,First Owner,13.5,2987.0,282.0,490Nm@ 1600rpm,5.0
Jeep Wrangler 2016-2019 3.6 4X4,2017,4100000,17000,Petrol,Individual,Automatic,First Owner,9.5,3604.0,280.0,347Nm@ 4300rpm,5.0
Jeep Wrangler 2016-2019 3.6 4X4,2017,4100000,17000,Petrol,Individual,Automatic,First Owner,9.5,3604.0,280.0,347Nm@ 4300rpm,5.0
Jeep Wrangler 2016-2019 3.6 4X4,2017,4100000,17000,Petrol,Individual,Automatic,First Owner,9.5,3604.0,280.0,347Nm@ 4300rpm,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
Toyota Qualis Fleet A3,2000,200000,100000,Diesel,Individual,Manual,First Owner,NaN,NaN,NaN,NaN,NaN
Hyundai Santro LS zipPlus,2000,140000,50000,Petrol,Individual,Manual,Second Owner,NaN,NaN,NaN,NaN,NaN
Hyundai Santro Xing XS eRLX Euro III,2006,145000,80000,Petrol,Individual,Manual,Second Owner,NaN,NaN,NaN,NaN,NaN
Ford Figo Aspire Facelift,2017,580000,165000,Diesel,Individual,Manual,First Owner,NaN,NaN,NaN,NaN,NaN
Maruti Swift 1.3 VXi,2006,130000,100000,Petrol,Individual,Manual,Second Owner,NaN,NaN,NaN,NaN,NaN

### Replace nan values with 0 to implement some manipulations

In [10]:
df2['mileage'] = df2['mileage'].replace({np.nan:0})
df2['mileage'] = df2['mileage'].astype(np.int16)
df2.head(5)

,year,sell,km,fuel,seller,transmission,owner,mileage,engine,power,torque,seats
name,,,,,,,,,,,,
Volvo XC90 T8 Excellence BSIV,2017,10000000,30000,Petrol,Individual,Automatic,First Owner,42,1969.0,400.0,640Nm@ 1740rpm,4.0
Mercedes-Benz S-Class S 350 CDI,2017,5850000,47000,Diesel,Dealer,Automatic,First Owner,13,2987.0,282.0,490Nm@ 1600rpm,5.0
Jeep Wrangler 2016-2019 3.6 4X4,2017,4100000,17000,Petrol,Individual,Automatic,First Owner,9,3604.0,280.0,347Nm@ 4300rpm,5.0
Jeep Wrangler 2016-2019 3.6 4X4,2017,4100000,17000,Petrol,Individual,Automatic,First Owner,9,3604.0,280.0,347Nm@ 4300rpm,5.0
Jeep Wrangler 2016-2019 3.6 4X4,2017,4100000,17000,Petrol,Individual,Automatic,First Owner,9,3604.0,280.0,347Nm@ 4300rpm,5.0

In [11]:
df2['engine'] = df2['engine'].replace({np.nan:0})
df2['engine'] = df2['engine'].astype(np.int32)
df2.head(5)

,year,sell,km,fuel,seller,transmission,owner,mileage,engine,power,torque,seats
name,,,,,,,,,,,,
Volvo XC90 T8 Excellence BSIV,2017,10000000,30000,Petrol,Individual,Automatic,First Owner,42,1969,400.0,640Nm@ 1740rpm,4.0
Mercedes-Benz S-Class S 350 CDI,2017,5850000,47000,Diesel,Dealer,Automatic,First Owner,13,2987,282.0,490Nm@ 1600rpm,5.0
Jeep Wrangler 2016-2019 3.6 4X4,2017,4100000,17000,Petrol,Individual,Automatic,First Owner,9,3604,280.0,347Nm@ 4300rpm,5.0
Jeep Wrangler 2016-2019 3.6 4X4,2017,4100000,17000,Petrol,Individual,Automatic,First Owner,9,3604,280.0,347Nm@ 4300rpm,5.0
Jeep Wrangler 2016-2019 3.6 4X4,2017,4100000,17000,Petrol,Individual,Automatic,First Owner,9,3604,280.0,347Nm@ 4300rpm,5.0

In [12]:
df2['power'] = df2['power'].replace({np.nan:0})
df2['power'] = df2['power'].astype(np.int16)
df2

,year,sell,km,fuel,seller,transmission,owner,mileage,engine,power,torque,seats
name,,,,,,,,,,,,
Volvo XC90 T8 Excellence BSIV,2017,10000000,30000,Petrol,Individual,Automatic,First Owner,42,1969,400,640Nm@ 1740rpm,4.0
Mercedes-Benz S-Class S 350 CDI,2017,5850000,47000,Diesel,Dealer,Automatic,First Owner,13,2987,282,490Nm@ 1600rpm,5.0
Jeep Wrangler 2016-2019 3.6 4X4,2017,4100000,17000,Petrol,Individual,Automatic,First Owner,9,3604,280,347Nm@ 4300rpm,5.0
Jeep Wrangler 2016-2019 3.6 4X4,2017,4100000,17000,Petrol,Individual,Automatic,First Owner,9,3604,280,347Nm@ 4300rpm,5.0
Jeep Wrangler 2016-2019 3.6 4X4,2017,4100000,17000,Petrol,Individual,Automatic,First Owner,9,3604,280,347Nm@ 4300rpm,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
Toyota Qualis Fleet A3,2000,200000,100000,Diesel,Individual,Manual,First Owner,0,0,0,NaN,NaN
Hyundai Santro LS zipPlus,2000,140000,50000,Petrol,Individual,Manual,Second Owner,0,0,0,NaN,NaN
Hyundai Santro Xing XS eRLX Euro III,2006,145000,80000,Petrol,Individual,Manual,Second Owner,0,0,0,NaN,NaN
Ford Figo Aspire Facelift,2017,580000,165000,Diesel,Individual,Manual,First Owner,0,0,0,NaN,NaN
Maruti Swift 1.3 VXi,2006,130000,100000,Petrol,Individual,Manual,Second Owner,0,0,0,NaN,NaN

In [13]:
df2['seats'] = df2['seats'].replace({np.nan:0})
df2['seats'] = df2['seats'].astype(np.int16)
df2

,year,sell,km,fuel,seller,transmission,owner,mileage,engine,power,torque,seats
name,,,,,,,,,,,,
Volvo XC90 T8 Excellence BSIV,2017,10000000,30000,Petrol,Individual,Automatic,First Owner,42,1969,400,640Nm@ 1740rpm,4
Mercedes-Benz S-Class S 350 CDI,2017,5850000,47000,Diesel,Dealer,Automatic,First Owner,13,2987,282,490Nm@ 1600rpm,5
Jeep Wrangler 2016-2019 3.6 4X4,2017,4100000,17000,Petrol,Individual,Automatic,First Owner,9,3604,280,347Nm@ 4300rpm,5
Jeep Wrangler 2016-2019 3.6 4X4,2017,4100000,17000,Petrol,Individual,Automatic,First Owner,9,3604,280,347Nm@ 4300rpm,5
Jeep Wrangler 2016-2019 3.6 4X4,2017,4100000,17000,Petrol,Individual,Automatic,First Owner,9,3604,280,347Nm@ 4300rpm,5
...,...,...,...,...,...,...,...,...,...,...,...,...
Toyota Qualis Fleet A3,2000,200000,100000,Diesel,Individual,Manual,First Owner,0,0,0,NaN,0
Hyundai Santro LS zipPlus,2000,140000,50000,Petrol,Individual,Manual,Second Owner,0,0,0,NaN,0
Hyundai Santro Xing XS eRLX Euro III,2006,145000,80000,Petrol,Individual,Manual,Second Owner,0,0,0,NaN,0
Ford Figo Aspire Facelift,2017,580000,165000,Diesel,Individual,Manual,First Owner,0,0,0,NaN,0
Maruti Swift 1.3 VXi,2006,130000,100000,Petrol,Individual,Manual,Second Owner,0,0,0,NaN,0

In [14]:
df2.to_sql('CarDetails.db', db)

8128

### Checking Tables in our db

In [15]:
query = "select name from sqlite_master where type = 'table';"

In [16]:
cursor.execute(query)
cursor.fetchall()

[('auto_info',), ('CarDetails.db',)]

Changing the name of the table that was already saved

In [17]:
cursor.execute("ALTER TABLE 'CarDetails.db' RENAME TO CarDetails;")
db.commit()

In [18]:
query = "select name from sqlite_master where type = 'table';"
cursor.execute(query)
cursor.fetchall()

[('auto_info',), ('CarDetails',)]

`pragma table_info`

In [19]:
cursor.execute('pragma table_info(auto_info);')
cursor.fetchall()

[(0, 'index', 'INTEGER', 0, None, 0),
 (1, 'company', 'TEXT', 0, None, 0),
 (2, 'body', 'TEXT', 0, None, 0),
 (3, 'wheel', 'REAL', 0, None, 0),
 (4, 'length', 'REAL', 0, None, 0),
 (5, 'engine', 'TEXT', 0, None, 0),
 (6, 'cylinders', 'TEXT', 0, None, 0),
 (7, 'horse', 'INTEGER', 0, None, 0),
 (8, 'milage', 'INTEGER', 0, None, 0),
 (9, 'price', 'INTEGER', 0, None, 0)]

### Reading DataBases table

In [20]:
query = "select * from auto_info where price > 10000"
df3 = pd.read_sql(query, db)
df3 = df3.set_index('index')
df3

,company,body,wheel,length,engine,cylinders,horse,milage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450
5,audi,sedan,99.8,177.3,ohc,five,110,19,15250
6,audi,wagon,105.8,192.7,ohc,five,110,19,18920
9,bmw,sedan,101.2,176.8,ohc,four,101,23,16430
10,bmw,sedan,101.2,176.8,ohc,four,101,23,16925
11,bmw,sedan,101.2,176.8,ohc,six,121,21,20970
13,bmw,sedan,103.5,189.0,ohc,six,182,16,30760
28,honda,sedan,96.5,175.4,ohc,four,101,24,12945
29,honda,sedan,96.5,169.1,ohc,four,100,25,10345
33,jaguar,sedan,113.0,199.6,dohc,six,176,15,32250
39,mazda,hatchback,95.3,169.0,rotor,two,101,17,11845
43,mazda,sedan,104.9,175.0,ohc,four,72,31,18344
44,mercedes-benz,sedan,110.0,190.9,ohc,five,123,22,25552
45,mercedes-benz,wagon,110.0,190.9,ohc,five,123,22,28248
57,nissan,sedan,100.4,184.6,ohcv,six,152,19,13499
79,toyota,wagon,104.5,187.8,dohc,six,156,19,15750
87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940
88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415

In [21]:
df3.to_sql('ExpensiveCars', db)

22

In [22]:
cursor.execute('select name from sqlite_master where type = "table";')
cursor.fetchall()

[('auto_info',), ('CarDetails',), ('ExpensiveCars',)]



---

In [23]:
newq = '''
        select year, sell, km, seller, owner, seats
        from CarDetails
        where year = 2017 and owner = "First Owner";
        '''

In [24]:
pd.read_sql(newq, db)

     year      sell      km      seller        owner  seats
0    2017  10000000   30000  Individual  First Owner      4
1    2017   5850000   47000      Dealer  First Owner      5
2    2017   4100000   17000  Individual  First Owner      5
3    2017   4100000   17000  Individual  First Owner      5
4    2017   4100000   17000  Individual  First Owner      5
..    ...       ...     ...         ...          ...    ...
906  2017    589000   41232      Dealer  First Owner      0
907  2017   2150000   27000      Dealer  First Owner      0
908  2017    600000   60000  Individual  First Owner      0
909  2017    600000   40000  Individual  First Owner      0
910  2017    580000  165000  Individual  First Owner      0

[911 rows x 6 columns]

### Creating an empty table

In [25]:
q = """
create table if not exists DreamCars(
  name varchar(100),
  year int,
  fuel varchar(100),
  price int
)
"""

In [26]:
cursor.execute(q)
db.commit()

In [27]:
cursor.execute('select name from sqlite_master where type = "table";')
cursor.fetchall()

[('auto_info',), ('CarDetails',), ('ExpensiveCars',), ('DreamCars',)]

DreamCars

In [28]:
cursor.execute('pragma table_info(DreamCars)')
cursor.fetchall()

[(0, 'name', 'varchar(100)', 0, None, 0),
 (1, 'year', 'INT', 0, None, 0),
 (2, 'fuel', 'varchar(100)', 0, None, 0),
 (3, 'price', 'INT', 0, None, 0)]

In [34]:
query = """
insert into DreamCars ('name', 'year', 'fuel', 'price')
values
('Toyota Supra', 1998, 'Petrol', 45000),
('Tesla Model S', 2021, 'Electric', 79999),
('Ford Mustang', 2015, 'Petrol', 35000),
('BMW M3', 2018, 'Petrol', 62000),
('Audi A6', 2020, 'Diesel', 50000),
('Porsche 911', 2017, 'Petrol', 95000),
('Honda NSX', 2005, 'Petrol', 70000),
('Lamborghini Huracan', 2022, 'Petrol', 200000),
('Chevrolet Camaro', 2016, 'Petrol', 33000),
('Nissan GT-R', 2014, 'Petrol', 80000);
"""

In [35]:
cursor.execute(query)
db.commit()

In [36]:
cursor.execute('select * from DreamCars')
cursor.fetchall()

[('Supra', 1998, 'Petrol', 10000),
 ('Toyota Supra', 1998, 'Petrol', 45000),
 ('Tesla Model S', 2021, 'Electric', 79999),
 ('Ford Mustang', 2015, 'Petrol', 35000),
 ('BMW M3', 2018, 'Petrol', 62000),
 ('Audi A6', 2020, 'Diesel', 50000),
 ('Porsche 911', 2017, 'Petrol', 95000),
 ('Honda NSX', 2005, 'Petrol', 70000),
 ('Lamborghini Huracan', 2022, 'Petrol', 200000),
 ('Chevrolet Camaro', 2016, 'Petrol', 33000),
 ('Nissan GT-R', 2014, 'Petrol', 80000)]

In [37]:
query = "select * from DreamCars"
pd.read_sql(query, db)

                   name  year      fuel   price
0                 Supra  1998    Petrol   10000
1          Toyota Supra  1998    Petrol   45000
2         Tesla Model S  2021  Electric   79999
3          Ford Mustang  2015    Petrol   35000
4                BMW M3  2018    Petrol   62000
5               Audi A6  2020    Diesel   50000
6           Porsche 911  2017    Petrol   95000
7             Honda NSX  2005    Petrol   70000
8   Lamborghini Huracan  2022    Petrol  200000
9      Chevrolet Camaro  2016    Petrol   33000
10          Nissan GT-R  2014    Petrol   80000

### Updating a table

In [38]:
cursor.execute('update DreamCars set year = 2000, price = 15000 where name = "Supra"')
db.commit()

We can see how year and price has changed in the row of Supra

In [39]:
pd.read_sql('select * from DreamCars', db)

                   name  year      fuel   price
0                 Supra  2000    Petrol   15000
1          Toyota Supra  1998    Petrol   45000
2         Tesla Model S  2021  Electric   79999
3          Ford Mustang  2015    Petrol   35000
4                BMW M3  2018    Petrol   62000
5               Audi A6  2020    Diesel   50000
6           Porsche 911  2017    Petrol   95000
7             Honda NSX  2005    Petrol   70000
8   Lamborghini Huracan  2022    Petrol  200000
9      Chevrolet Camaro  2016    Petrol   33000
10          Nissan GT-R  2014    Petrol   80000

### Deleting DataBase

In [41]:
query = "delete from DreamCars where name = 'Audi A6'"
cursor.execute(query)
db.commit()

We have deleted from our table the row with 'Audi A6'

In [43]:
pd.read_sql('select * from DreamCars', db)

                  name  year      fuel   price
0                Supra  2000    Petrol   15000
1         Toyota Supra  1998    Petrol   45000
2        Tesla Model S  2021  Electric   79999
3         Ford Mustang  2015    Petrol   35000
4               BMW M3  2018    Petrol   62000
5          Porsche 911  2017    Petrol   95000
6            Honda NSX  2005    Petrol   70000
7  Lamborghini Huracan  2022    Petrol  200000
8     Chevrolet Camaro  2016    Petrol   33000
9          Nissan GT-R  2014    Petrol   80000

### Deleting Table from DataBase

In [44]:
cursor.execute('drop table DreamCars')

In [45]:
db.commit()

Table `DreamCars` has been deleted

In [46]:
cursor.execute('select name from sqlite_master where type = "table"')
cursor.fetchall()

[('auto_info',), ('CarDetails',), ('ExpensiveCars',)]

### Data Exchanging

In [48]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/world_population.csv', index_col = 'rank')
df

               country     density   densityMi   pop2021     area
rank
1                Macau  21946.4667  56841.3487   658.394       30
2               Monaco  19755.5000  51166.7450    39.511        2
3            Singapore   8305.1915  21510.4461  5896.686      710
4            Hong Kong   6841.3134  17719.0017  7552.810     1104
5            Gibraltar   5616.3333  14546.3033    33.698        6
...                ...         ...         ...       ...      ...
228            Namibia      3.1338      8.1166  2587.344   825615
229     Western Sahara      2.3003      5.9577   611.875   266000
230           Mongolia      2.1286      5.5129  3329.289  1564110
231   Falkland Islands      0.2902      0.7517     3.533    12173
232          Greenland      0.0263      0.0680    56.877  2166086

[232 rows x 5 columns]

In [53]:
uz = df[df['country'] == 'Uzbekistan']
uz

         country  density  densityMi    pop2021    area
rank
133   Uzbekistan  75.8511   196.4542  33935.763  447400

In [64]:
rank = uz.index.values[0]
rank

np.int64(133)

In [66]:
country = uz.at[rank, 'country']
density = uz.at[rank, 'density']
densityMi = uz.at[rank, 'densityMi']
pop = uz.at[rank, 'pop2021']
area = uz.at[rank, 'area']

Creating another empty table

In [67]:
query = """
create table WorldPop(
  country varchar(100),
  density real,
  densityMi real,
  pop real,
  area integer
)
"""

In [69]:
cursor.execute(query)
db.commit()

In [70]:
cursor.execute('select name from sqlite_master where type = "table"')
cursor.fetchall()

[('auto_info',), ('CarDetails',), ('ExpensiveCars',), ('WorldPop',)]

In [78]:
cursor.execute('pragma table_info(WorldPop)')
cursor.fetchall()

[(0, 'country', 'varchar(100)', 0, None, 0),
 (1, 'density', 'REAL', 0, None, 0),
 (2, 'densityMi', 'REAL', 0, None, 0),
 (3, 'pop', 'REAL', 0, None, 0),
 (4, 'area', 'INTEGER', 0, None, 0)]

Insertion process

In [84]:
query = f"""
insert into worldPop(country, density, densityMi, pop, area)
values('{country}', {density}, {densityMi}, {pop}, {area})
"""

In [85]:
cursor.execute(query)
db.commit()

We have inseted an information from csv to our table in db, which is ususally used to make process of insertion automatic

In [86]:
query = 'select * from WorldPop'
pd.read_sql(query, db)

      country  density  densityMi        pop    area
0  Uzbekistan  75.8511   196.4542  33935.763  447400