### Data Science and AI Practicum

### Working with SQLite

In [ ]:
import pandas as pd
import sqlite3 as sql
from pprint import pprint as print

In [ ]:
!unzip sample_db.zip

Archive:  sample_db.zip
replace sample.db? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
 extracting: sample.db

In [ ]:
examdb = sql.connect("sample.db")
cursor = examdb.cursor()

In [ ]:
cursor.execute("select name from sqlite_master where type = 'table';")
cursor.fetchall()

[('users',), ('orders',)]

In [ ]:
cursor.execute("select count(*) from users")
cursor.fetchone()

(50,)

--------------------------------------------------------------------------------

### Fetch one

cursor.fetchone()

In [ ]:
cursor.execute("select * from users")
cursor.fetchone()

(1, 'User1', 20)

--------------------------------------------------------------------------------

### Fetch all

cursor.fetchall()

In [ ]:
cursor.execute("select * from users")
cursor.fetchall()

[(1, 'User1', 20),
 (2, 'User2', 21),
 (3, 'User3', 22),
 (4, 'User4', 23),
 (5, 'User5', 24),
 (6, 'User6', 25),
 (7, 'User7', 26),
 (8, 'User8', 27),
 (9, 'User9', 28),
 (10, 'User10', 29),
 (11, 'User11', 20),
 (12, 'User12', 21),
 (13, 'User13', 22),
 (14, 'User14', 23),
 (15, 'User15', 24),
 (16, 'User16', 25),
 (17, 'User17', 26),
 (18, 'User18', 27),
 (19, 'User19', 28),
 (20, 'User20', 29),
 (21, 'User21', 20),
 (22, 'User22', 21),
 (23, 'User23', 22),
 (24, 'User24', 23),
 (25, 'User25', 24),
 (26, 'User26', 25),
 (27, 'User27', 26),
 (28, 'User28', 27),
 (29, 'User29', 28),
 (30, 'User30', 29),
 (31, 'User31', 20),
 (32, 'User32', 21),
 (33, 'User33', 22),
 (34, 'User34', 23),
 (35, 'User35', 24),
 (36, 'User36', 25),
 (37, 'User37', 26),
 (38, 'User38', 27),
 (39, 'User39', 28),
 (40, 'User40', 29),
 (41, 'User41', 20),
 (42, 'User42', 21),
 (43, 'User43', 22),
 (44, 'User44', 23),
 (45, 'User45', 24),
 (46, 'User46', 25),
 (47, 'User47', 26),
 (48, 'User48', 27),
 (49, 'User49', 28),
 (50, 'User50', 29)]

--------------------------------------------------------------------------------

### Fetch any

cursor.fetchany(n)

In [ ]:
cursor.execute("select * from users where age % 2 = 0")
cursor.fetchmany(10)

[(1, 'User1', 20),
 (3, 'User3', 22),
 (5, 'User5', 24),
 (7, 'User7', 26),
 (9, 'User9', 28),
 (11, 'User11', 20),
 (13, 'User13', 22),
 (15, 'User15', 24),
 (17, 'User17', 26),
 (19, 'User19', 28)]

--------------------------------------------------------------------------------

In [ ]:
cursor.execute("select * from users")
column_names = [description[0] for description in cursor.description]
column_names

['id', 'name', 'age']

book = dict([("title", "Python Basics"), ("pages", 320), ("author", "John Doe")])

book

In [ ]:
cursor.execute("pragma table_info (users);")
cursor.fetchall()

[(0, 'id', 'INTEGER', 0, None, 0),
 (1, 'name', 'TEXT', 0, None, 0),
 (2, 'age', 'INTEGER', 0, None, 0)]

In [ ]:
cursor.execute("select * from orders")
oreders2 = cursor.fetchall()

In [38]:
df_oreder = pd.read_sql("select * from orders", examdb)
df_oreder

    id  user_id  amount
0    1        1     100
1    2        2     105
2    3        3     110
3    4        4     115
4    5        5     120
5    6        6     125
6    7        7     130
7    8        8     135
8    9        9     140
9   10       10     145
10  11       11     150
11  12       12     155
12  13       13     160
13  14       14     165
14  15       15     170
15  16       16     175
16  17       17     180
17  18       18     185
18  19       19     190
19  20       20     195
20  21       21     200
21  22       22     205
22  23       23     210
23  24       24     215
24  25       25     220
25  26       26     225
26  27       27     230
27  28       28     235
28  29       29     240
29  30       30     245
30  31       31     250
31  32       32     255
32  33       33     260
33  34       34     265
34  35       35     270
35  36       36     275
36  37       37     280
37  38       38     285
38  39       39     290
39  40       40     295
40  41       41     300
41  42       42     305
42  43       43     310
43  44       44     315
44  45       45     320
45  46       46     325
46  47       47     330
47  48       48     335
48  49       49     340
49  50       50     345

In [41]:
df = pd.read_sql("select * from users", examdb, index_col = 'id')
df

      name  age
id
1    User1   20
2    User2   21
3    User3   22
4    User4   23
5    User5   24
6    User6   25
7    User7   26
8    User8   27
9    User9   28
10  User10   29
11  User11   20
12  User12   21
13  User13   22
14  User14   23
15  User15   24
16  User16   25
17  User17   26
18  User18   27
19  User19   28
20  User20   29
21  User21   20
22  User22   21
23  User23   22
24  User24   23
25  User25   24
26  User26   25
27  User27   26
28  User28   27
29  User29   28
30  User30   29
31  User31   20
32  User32   21
33  User33   22
34  User34   23
35  User35   24
36  User36   25
37  User37   26
38  User38   27
39  User39   28
40  User40   29
41  User41   20
42  User42   21
43  User43   22
44  User44   23
45  User45   24
46  User46   25
47  User47   26
48  User48   27
49  User49   28
50  User50   29

In [43]:
df2 = pd.read_sql("select id, name, age from users limit 20", examdb, index_col = 'id')
df2

      name  age
id
1    User1   20
2    User2   21
3    User3   22
4    User4   23
5    User5   24
6    User6   25
7    User7   26
8    User8   27
9    User9   28
10  User10   29
11  User11   20
12  User12   21
13  User13   22
14  User14   23
15  User15   24
16  User16   25
17  User17   26
18  User18   27
19  User19   28
20  User20   29