### DataScience and AI Practicum

### Pandas: Filtering Data

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/merc.csv')
df.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,SLK,2005,5200,Automatic,63000,Petrol,325,32.1,1.8
1,S Class,2017,34948,Automatic,27000,Hybrid,20,61.4,2.1
2,SL CLASS,2016,49948,Automatic,6200,Petrol,555,28.0,5.5
3,G Class,2016,61948,Automatic,16000,Petrol,325,30.4,4.0
4,G Class,2016,73948,Automatic,4000,Petrol,325,30.1,4.0

In [7]:
models = df["model"].unique()
models.sort()
models

array([' A Class', ' B Class', ' C Class', ' CL Class', ' CLA Class',
       ' CLC Class', ' CLK', ' CLS Class', ' E Class', ' G Class',
       ' GL Class', ' GLA Class', ' GLB Class', ' GLC Class',
       ' GLE Class', ' GLS Class', ' M Class', ' R Class', ' S Class',
       ' SL CLASS', ' SLK', ' V Class', ' X-CLASS', '180', '200', '220',
       '230'], dtype=object)

`.UNIQUE()` this function gets unique values only that means, same values will not be repeated

In [5]:
df["model"]

0               SLK
1           S Class
2          SL CLASS
3           G Class
4           G Class
            ...
13114       C Class
13115       B Class
13116     GLC Class
13117     CLS Class
13118       S Class
Name: model, Length: 13119, dtype: object

In [8]:
engine = df["engineSize"].unique()
engine

array([1.8, 2.1, 5.5, 4. , 6.2, 3.5, 2. , 1.5, 3. , 1.3, 2.9, 4.7, 2.5,
       1.6, 2.2, 2.3, 6. , 3.2, 0. , 5. , 2.7, 3.7, 5.4, 4.3, 1.7, 1.4])

In [12]:
engine.size

26

In this dataset of 30000 cars we got only 4 categories of fuel that cars work on

In [13]:
fuel = df["fuelType"].unique()
fuel

array(['Petrol', 'Hybrid', 'Diesel', 'Other'], dtype=object)

`.value_counts()` gives an amount of values on unque related values

In [16]:
df["fuelType"].value_counts()

fuelType
Diesel    9187
Petrol    3752
Hybrid     173
Other        7
Name: count, dtype: int64

In [17]:
df["year"].value_counts()

year
2019    4553
2017    2381
2016    1971
2018    1467
2015     991
2020     719
2014     491
2013     292
2012      57
2010      38
2011      38
2007      22
2009      17
2008      16
2004      13
2001      10
2005       9
2002       9
2006       8
2003       7
1998       4
2000       3
1997       1
1999       1
1970       1
Name: count, dtype: int64

Filtering values using `.isin()`: returns false and true

In [38]:
filter = [2019, 2018]
yfilter = df["year"].isin(filter)
df[yfilter]

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
6,GLE Class,2018,30948,Automatic,16000,Diesel,145,47.9,2.1
8,G Class,2019,139948,Automatic,12000,Petrol,145,21.4,4.0
12,B Class,2019,23750,Automatic,278,Diesel,145,55.4,2.0
13,GLC Class,2019,67980,Automatic,5500,Petrol,145,21.7,4.0
17,GLE Class,2019,56800,Automatic,2483,Petrol,145,29.5,3.0
...,...,...,...,...,...,...,...,...,...
13111,B Class,2019,19344,Automatic,15257,Petrol,145,45.6,1.3
13112,C Class,2019,30399,Automatic,5000,Diesel,145,61.4,2.0
13116,GLC Class,2019,30999,Automatic,11612,Diesel,145,41.5,2.1
13117,CLS Class,2019,37990,Automatic,2426,Diesel,145,45.6,2.0
13118,S Class,2019,54999,Automatic,2075,Diesel,145,52.3,2.9

In [36]:
m_filter = ([" A Class", " SLK"])
filterm = df["model"].isin(m_filter)
filterm

0         True
1        False
2        False
3        False
4        False
         ...
13114    False
13115    False
13116    False
13117    False
13118    False
Name: model, Length: 13119, dtype: bool

In [37]:
df[filterm] # getting columns appropriate to the filter

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,SLK,2005,5200,Automatic,63000,Petrol,325,32.1,1.8
10,A Class,2020,32980,Automatic,606,Petrol,145,35.8,2.0
11,A Class,2020,26980,Automatic,1000,Diesel,145,62.8,1.5
33,A Class,2020,28128,Automatic,2563,Petrol,145,47.9,1.3
34,A Class,2019,23184,Manual,1173,Petrol,145,44.8,1.3
...,...,...,...,...,...,...,...,...,...
13060,A Class,2017,109495,Automatic,1755,Petrol,145,24.8,4.0
13066,A Class,2019,23440,Automatic,10124,Petrol,145,53.3,1.3
13090,A Class,2015,12995,Automatic,34665,Diesel,20,70.6,1.5
13108,SLK,2016,17499,Automatic,30128,Diesel,30,70.6,2.1
13109,A Class,2017,16499,Automatic,20477,Diesel,145,68.9,2.1

In [25]:
df2 = df["model"].isin(m_filter)
df2

0         True
1        False
2        False
3        False
4        False
         ...
13114    False
13115    False
13116    False
13117    False
13118    False
Name: model, Length: 13119, dtype: bool

In [29]:
new_filter = df["year"].isin([2019, 2018])
df[new_filter] # we get all the columns related to the filter

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
6,GLE Class,2018,30948,Automatic,16000,Diesel,145,47.9,2.1
8,G Class,2019,139948,Automatic,12000,Petrol,145,21.4,4.0
12,B Class,2019,23750,Automatic,278,Diesel,145,55.4,2.0
13,GLC Class,2019,67980,Automatic,5500,Petrol,145,21.7,4.0
17,GLE Class,2019,56800,Automatic,2483,Petrol,145,29.5,3.0
...,...,...,...,...,...,...,...,...,...
13111,B Class,2019,19344,Automatic,15257,Petrol,145,45.6,1.3
13112,C Class,2019,30399,Automatic,5000,Diesel,145,61.4,2.0
13116,GLC Class,2019,30999,Automatic,11612,Diesel,145,41.5,2.1
13117,CLS Class,2019,37990,Automatic,2426,Diesel,145,45.6,2.0
13118,S Class,2019,54999,Automatic,2075,Diesel,145,52.3,2.9

In [39]:
df[df["year"]>200]

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,SLK,2005,5200,Automatic,63000,Petrol,325,32.1,1.8
1,S Class,2017,34948,Automatic,27000,Hybrid,20,61.4,2.1
2,SL CLASS,2016,49948,Automatic,6200,Petrol,555,28.0,5.5
3,G Class,2016,61948,Automatic,16000,Petrol,325,30.4,4.0
4,G Class,2016,73948,Automatic,4000,Petrol,325,30.1,4.0
...,...,...,...,...,...,...,...,...,...
13114,C Class,2020,35999,Automatic,500,Diesel,145,55.4,2.0
13115,B Class,2020,24699,Automatic,2500,Diesel,145,55.4,2.0
13116,GLC Class,2019,30999,Automatic,11612,Diesel,145,41.5,2.1
13117,CLS Class,2019,37990,Automatic,2426,Diesel,145,45.6,2.0
13118,S Class,2019,54999,Automatic,2075,Diesel,145,52.3,2.9

In [ ]:
m_filter = ([" A Class", " SLK"])

filterm = df["model"].isin(m_filter)

In [40]:
df[df["model"].isin([" A Class", " SLK"])] # the same code as above but in more simple way

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,SLK,2005,5200,Automatic,63000,Petrol,325,32.1,1.8
10,A Class,2020,32980,Automatic,606,Petrol,145,35.8,2.0
11,A Class,2020,26980,Automatic,1000,Diesel,145,62.8,1.5
33,A Class,2020,28128,Automatic,2563,Petrol,145,47.9,1.3
34,A Class,2019,23184,Manual,1173,Petrol,145,44.8,1.3
...,...,...,...,...,...,...,...,...,...
13060,A Class,2017,109495,Automatic,1755,Petrol,145,24.8,4.0
13066,A Class,2019,23440,Automatic,10124,Petrol,145,53.3,1.3
13090,A Class,2015,12995,Automatic,34665,Diesel,20,70.6,1.5
13108,SLK,2016,17499,Automatic,30128,Diesel,30,70.6,2.1
13109,A Class,2017,16499,Automatic,20477,Diesel,145,68.9,2.1

Getting cars only related to `A Class and SLK` and the only ones that are newer than 2000 and working on Petrol and Diesel

In [43]:
df[(df["model"].isin([" A Class", " SLK"])) & (df["year"]>2000) & df["fuelType"].isin(["Petrol", "Diesel"])]

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,SLK,2005,5200,Automatic,63000,Petrol,325,32.1,1.8
10,A Class,2020,32980,Automatic,606,Petrol,145,35.8,2.0
11,A Class,2020,26980,Automatic,1000,Diesel,145,62.8,1.5
33,A Class,2020,28128,Automatic,2563,Petrol,145,47.9,1.3
34,A Class,2019,23184,Manual,1173,Petrol,145,44.8,1.3
...,...,...,...,...,...,...,...,...,...
13060,A Class,2017,109495,Automatic,1755,Petrol,145,24.8,4.0
13066,A Class,2019,23440,Automatic,10124,Petrol,145,53.3,1.3
13090,A Class,2015,12995,Automatic,34665,Diesel,20,70.6,1.5
13108,SLK,2016,17499,Automatic,30128,Diesel,30,70.6,2.1
13109,A Class,2017,16499,Automatic,20477,Diesel,145,68.9,2.1